lib/yellr_web/router.ex
defmodule YellrWeb.Router do
  use YellrWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :check_login do
    plug Guardian.Plug.VerifySession, claims: %{"typ" => "access"},
      module: Yellr.Authentication.Guardian,
      error_handler: YellrWeb.SessionsController
    plug Guardian.Plug.VerifyHeader, claims: %{"typ" => "access"},
      module: Yellr.Authentication.Guardian,
      error_handler: YellrWeb.SessionsController
    plug Guardian.Plug.EnsureAuthenticated,
      module: Yellr.Authentication.Guardian,
      error_handler: YellrWeb.SessionsController
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug YellrWeb.ApiKeyPlug
  end

  scope "/api", YellrWeb.Api do
    pipe_through :api

    resources "/build_results", BuildResultsController, only: [:create]
  end

  scope "/", YellrWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/sessions", SessionsController, only: [:new, :create]
  end

  scope "/", YellrWeb do
    pipe_through([:browser, :check_login])

    delete "/sessions", SessionsController, :destroy

    resources "/branches", BranchesController, only: [:new, :create, :delete, :update]
    resources "/projects", ProjectsController, except: [:delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", YellrWeb do
  #   pipe_through :api
  # end
end

lib/yellr/data/project.ex
defmodule Yellr.Data.Project do
  use Ecto.Schema
  @timestamps_opts [type: :utc_datetime_usec]

  import Ecto.Changeset

  alias Yellr.Data.Project
  alias Yellr.Data.Branch

  @type t :: %__MODULE__{

  }

  schema "projects" do
    field :name, :string
    field :repository_url, :string

    has_many :branches, Branch
    timestamps()
  end

  def changeset(%Project{} = rec, attrs) do
    rec
    |> cast(attrs, [:name, :repository_url])
    |> validate_required([:name, :repository_url])
    |> validate_length(:name, min: 1, max: 512)
    |> validate_length(:repository_url, min: 1, max: 2048)
  end
end

lib/yellr/queries/projects.ex
defmodule Yellr.Queries.Projects do
  import Ecto.Query

  alias Yellr.Repo
  alias Yellr.Data.Project

  @spec project_list() ::
    [Project.t()]
  def project_list() do
    query = (from p in Project)
    Repo.all(query)
  end

  @spec project_by_id_with_branches(any()) ::
    Project.t() | nil
  def project_by_id_with_branches(project_id) do
    query = (
      from p in Project,
        where: p.id == ^project_id,
        preload: [:branches]
    )
    Repo.one(query)
  end
end

lib/yellr_web/controllers/projects_controller.ex
defmodule YellrWeb.ProjectsController do
  use YellrWeb, :controller

  def new(conn, _params) do
    project = Yellr.new_project_creation_request()
    render(conn, "new.html", %{form: project})
  end

  def create(conn, %{"project" => params}) do
    result = Yellr.create_project_from_params(params)
    case result do
      {:error, cs} -> render(conn, "new.html", %{form: cs})
      {:ok, record} -> redirect(conn, to: YellrWeb.Router.Helpers.projects_path(conn, :show, record.id))
    end
  end

  def edit(conn, %{"id" => project_id}) do
    project = Yellr.get_editable_project(project_id)
    render(conn, "edit.html", %{form: project, id: project_id})
  end

  def update(conn, %{"project" => params, "id" => project_id}) do
    result = Yellr.update_project_from_params(project_id, params)
    case result do
      {:error, cs} -> render(conn, "edit.html", %{form: cs, id: project_id})
      {:ok, record} -> redirect(conn, to: YellrWeb.Router.Helpers.projects_path(conn, :show, record.id))
    end
  end

  def index(conn, _params) do
    projects = Yellr.project_list()
    render(conn, "index.html", %{projects: projects})
  end

  def show(conn, %{"id" => project_id}) do
    project = Yellr.project_by_id_with_branches(project_id)
    render(conn, "show.html", %{project: project})
  end
end

lib/yellr_web/views/projects_view.ex
defmodule YellrWeb.ProjectsView do
  use YellrWeb, :view

  @spec sort_branches_for_display([Yellr.Data.Branch]) :: [Yellr.Data.Branch]
  def sort_branches_for_display(branches) do
    Enum.sort_by(branches, fn(b) -> b.name end)
  end
end

lib/yellr_web/templates/projects/edit.html.eex
<h1>Update Project</h1>
<div class="row">
<div class="col-sm-12">
<%= form_for @form, Routes.projects_path(@conn, :update, @id), [as: :project, method: :put], fn f -> %>
<div class="form-group">
  <%= label f, :name, "Name" %>
  <%= text_input f, :name, class: "form-control" %>
  <%= error_tag @form, :name %>
</div>
<div class="form-group">
  <%= label f, :repository_url, "Repository Url" %>
  <%= text_input f, :repository_url, class: "form-control" %>
  <%= error_tag @form, :repository_url %>
</div>
<%= submit "Submit", class: "btn btn-primary" %>
<% end %>
</div>
</div>

lib/yellr_web/templates/projects/index.html.eex
<div class="row">
<h1>Projects</h1>
</div>
<div class="row">
<%= link("New Project", to: Routes.projects_path(@conn, :new), class: "btn btn-primary") %>
</div>
<div class="row">
<ul>
<%= for project <- @projects do %>
<li><%= link(project.name, to: Routes.projects_path(@conn, :show, project.id))%> - <%= project.repository_url%></li>
<% end %>
</ul>
</div>

lib/yellr_web/templates/projects/new.html.eex
<h1>New Project</h1>
<div class="row">
<div class="col-sm-12">
<%= form_for @form, Routes.projects_path(@conn, :create), [as: :project], fn f -> %>
<div class="form-group">
  <%= label f, :name, "Name" %>
  <%= text_input f, :name, class: "form-control" %>
  <%= error_tag @form, :name %>
</div>
<div class="form-group">
  <%= label f, :repository_url, "Repository Url" %>
  <%= text_input f, :repository_url, class: "form-control" %>
  <%= error_tag @form, :repository_url %>
</div>
<%= submit "Submit", class: "btn btn-primary" %>
<% end %>
</div>
</div>

lib/yellr_web/templates/projects/show.html.eex
<div class="row">
  <h1><%= @project.name %></h1>
</div>
<div class="row">
<%= link("Edit Project", to: Routes.projects_path(@conn, :edit, @project.id), class: "btn btn-primary") %>
</div>
<div class="row">
  <dl>
    <dt>Repository URL</dt>
    <dd><%= @project.repository_url %></dd>
  </dl>
</div>
<div class="row">
  <h2>Branches</h2>
</div>
<div class="row">
  <%= link("New Branch", to: Routes.branches_path(@conn, :new, project_id: @project.id), class: "btn btn-primary") %>
</div>
<%= if Enum.any?(@project.branches) do %>
  <div class="row">
  <table class="table">
    <thead>
      <tr>
        <th>Branch Name</th>
        <th>Monitored?</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= for branch <- sort_branches_for_display(@project.branches) do %>
        <tr>
          <td><%= branch.name %></td>
          <td><%= branch.monitored %></td>
          <td>
            <%= if branch.monitored do %>
              <%= link "Unmonitor", to: Routes.branches_path(@conn, :update, branch.id, monitor: !branch.monitored), method: :put, class: "btn btn-secondary" %>
            <% else %>
              <%= link "Monitor", to: Routes.branches_path(@conn, :update, branch.id, monitor: !branch.monitored), method: :put, class: "btn btn-success" %>
            <% end %>
            <%= link "Destroy", to: Routes.branches_path(@conn, :delete, branch.id), method: :delete, class: "btn btn-danger", data: [confirm: "This will destroy all results as well, are you sure?"] %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
<% end %>